### ISSUE TITLE
Návrh reputačného systému pre FEIoverflow

### ISSUE THREAD

**Issue by xmalyp1** [Kyslik/feioverflow#11]
Ako hodnotiť odpovede/otázky/komenty.
Odznaky, body a iné...

Motívacia používať našu službu študentmi FEI...

**Comment by Kyslik** [comment]
Myslim ze done, mozno chybaju "pravomoci" kto co moze ked ma napr 100 reputacnych bodov atd...


V dokumente som popisal reputaciu, odznaky, aj nejake prvky hlasovanie + komentovania.
