### ISSUE TITLE
Body of email

### ISSUE THREAD

**Issue by xmalyp1** [Kyslik/feioverflow#22]
Navrhnit v HTML telo správy, ktoré sa bude posielať pri registrácii používateľom.....
Logo Feioverflow....+ dáta atď.

**Comment by Kyslik** [comment]
V tomto commite https://github.com/Kyslik/feioverflow/commit/e5c705fb6d68a6644eae1d230796fe3f10786d34 je body, malo by to ficat vsade v prehliadacoch (mail klientoch). Treba tam len dat teda unikatny link do a href. Mozno oslovenie ale s tym by som sa nezapodieval.
