### ISSUE TITLE
Vytvor vo QuestionDAO metodu na vyhladavanie na zaklade klucovych slov

### ISSUE THREAD

**Issue by xmalyp1** [Kyslik/feioverflow#25]
Vytvor NamedQuery ktora vyhlada questions na zaklade zadanych klucovych slov.

- Klucove slovo treba kontrolovat minimalne v tagoch danej Q. a v nadpise !

**Comment by xmalyp1** [comment]
@juvraniak ako sme natom s týmto? Nie je to ani commitnuté ani nič,

**Comment by juvraniak** [comment]
Hotovo
