### ISSUE TITLE
Vyhladavanie na uvodnej obrazovke.

### ISSUE THREAD

**Issue by xmalyp1** [Kyslik/feioverflow#30]
Na úvodnej obrazovke sa nachadza field na vyhladavanie....

Implementuj metodu, ktorá zozbiera otázky spojené s klúčovým slovom (tag, slovo v nadpise etc) a vytvor stranku _search.xhtml _ , kde tieto výsledky zobrazíš. Stránka search.xhtml bude vyzerat rovnako ako _mainPage.xhtml_ len tam nebude field na vyhladávanie ale nadpis -
  Výsledky vyhľadavánia : _klúčové slovo_

**Comment by juvraniak** [comment]
Quera vytvorena, dnes dorobim aj page

**Comment by juvraniak** [comment]
Hotovo, pri zisteni nedostatku vytvorit bug.
