### ISSUE TITLE
Finálna dokumentácia

### ISSUE THREAD

**Issue by xmalyp1** [Kyslik/feioverflow#32]
Vytvor finálnu dokumentáciu, ktorá sa bude skladat z:

- Analýza riešení (Q A systems)
- Navrh rieśenia ( systemova specifikacia)
- Pouzivatelsky manual - este nemame....

Forma dokumentu má byt ako na zaverecnych pracach.

**Comment by Kyslik** [comment]
@xmalyp1 @juvraniak @matusvida @Martineees ak mate nejake veci co maju v dokumentacii **urcite** byt, napiste sem.  
Budem to pisat v LaTeXe (sharelatex.com); snad to prida na "kvalite" TP ;)

**Comment by xmalyp1** [comment]
dokument o LDAP pripojení daj ako prílohu ([link](https://github.com/Kyslik/feioverflow/commit/4203cd2eb768a8295dd6d3dafa844a0a20c2e7ea)) + všetky zápisnice tam musia byť ako príloha

**Comment by Kyslik** [comment]
Poprosim vas o screenshoty, s popisom (popis v nazve); bud dajte na gitgub v podobe commitu; alebo rovno sem. Alebo popis v nazve na slacku.

**Comment by Kyslik** [comment]
@xmalyp1  "ako prilohu" znamena co? kedze zapisnice mozeme jednoducho pripojit na elektronicke medium a v dokumente iba spomenut ze je... 

Dokument o LDAP nejako spracujem a pripojim samozrejme do final dokumentacie.

Zatial je ("sablona s logom nazov prace atd..") uvod / zaver, specifikacia poziadaviek, testovanie.

Treba este navrh riesenia (diagramy doplnim), implementaciu, analyzu (po dohode pridam analyzu co sme kazdy robili nejake excerpty), instalacny guide, a pouzivatelska prirucka.

**Comment by xmalyp1** [comment]
@Kyslik No ja neviem moze to byt ako priloha alebo iba v elektronickej forme....podla mna pridat tych 8 nebude nikomu vadit ako jedna cast PRILOH. Aj LDAP moze byt ako priloha..... Navrh riesenia a tieto veci mame predsa v systemovej specifikaciii......

**Comment by Kyslik** [comment]
Pridavam konkretne link k dokumentacii https://github.com/Kyslik/feioverflow/blob/documentation/final-documentation-latex/draft-pdf/output.pdf

(link je vzdy aktualny)
