### ISSUE TITLE
Vytvorenie krátkeho dokumentu o pripojení k LDAP

### ISSUE THREAD

**Issue by xmalyp1** [Kyslik/feioverflow#34]
Vytvor krátky dokument o pripojení k LDAP serverom pre feioverflow. Riešenie treba aj otestovať.

**Comment by xmalyp1** [comment]
Done @Kyslik  ak budes robit tu dokumentaciu napis toto treba ktomu pripojit tiez.

**Comment by Kyslik** [comment]
@xmalyp1  ano budem robit dokumentaciu, worry not; este nie je znamy deadline?
