### ISSUE TITLE
Prevzatie oficiálneho zadania

### ISSUE THREAD

**Issue by xmalyp1** [Kyslik/feioverflow#35]
K dokumentácii potrebujeme aj oficiálne znenie zadania. Je potrebné ho prevziať.

Viď. info: 

Zadanie si môžete vyzdvihnúť od 16.05 do 20.05.2016 v C 505.

**Comment by xmalyp1** [comment]
@Kyslik pls closeni issue hned ako si to prebral aby sme sa uistil ze ho mame :+1:

**Comment by Kyslik** [comment]
Ok done; pak termin sa bude posuvat (s velkou pravdep) este dalej. Nevedia presne kedy no Sabikova hovorila ze bude.
