### ISSUE TITLE
Nefunkčný progres bar

### ISSUE THREAD

**Issue by xmalyp1** [Kyslik/feioverflow#7]
Progres bar nie je funkcny + nereaguje na zmenu hodnoty value.

**Comment by Kyslik** [comment]
Tak mozeme close :)

**Comment by Kyslik** [comment]
Teda malo by sa normalne menit width (manualne) a "text"
```
="width: 50%">
          <span class="sr-only">50%</span>
```

Ostatne `aria-valuenow` moze byt deleted...
